/*CONSULTAS*/
/*Escribir una consulta que despliegue la fecha del sistema (SYSDATE), etiquetar la columna con el nombre “Date”.*/
SELECT (SYSDATE) AS "DATE" FROM DUAL;
 
/*Escribir una consulta que despliegue el nombre del departamento en minúsculas, de la tabla DEPARTMENTS.*/
SELECT LOWER(DEPARTMENT_NAME) AS "DEPARTAMENTOS" FROM DEPARTMENTS;

/*Escribir una consulta que despliegue solo la primera letra de cada palabra en mayúsculas, del campo nombre del país (COUNTRY_NAME) de la tabla COUNTRIES.*/
SELECT UPPER (SUBSTR (COUNTRY_NAME, 1, 1)) AS "PRIMERA LETRA", (UPPER(COUNTRY_NAME)) AS "NOMBRE COMPLETO" FROM COUNTRIES;
 
/*Dada la función MONTHS_BETWEEN, obtener su edad.*/
SELECT ROUND (MONTHS_BETWEEN (SYSDATE, TO_DATE('27-03-2000','DD-MM-YYYY'))/12) AS "EDAD" FROM DUAL;

/*A partir de la tabla EMPLOYEES, obtener la fecha de alta formateada, de manera que aparezca, el nombre del mes con todas sus letras (MONTH), el número del día del mes (DD) y el año (YYYY).*/
SELECT CONCAT (CONCAT (FIRST_NAME, ' '), LAST_NAME) AS "NOMBRE COMPLETO", TO_CHAR (HIRE_DATE, 'FMMONTH DD, YYYY') AS "FECHA DE CONTRATO" FROM EMPLOYEES;
 
/*Encontrar el salario más alto, más bajo, la suma de los salarios y el salario promedio de todos los empleados. Etiqueta las columnas como “Máximo” “Mínimo” “Suma” “Promedio”. Se deben redondear los resultados.*/
SELECT MAX(SALARY) AS "MAXIMO", MIN(SALARY) AS "MINIMO", SUM(SALARY) AS "SUMA", ROUND(AVG(SALARY)) AS "PROMEDIO" FROM EMPLOYEES;
 
/*El departamento RH necesita el siguiente reporte: Conocer el número de empleados con el mismo nombre.*/
SELECT FIRST_NAME AS "NOMBRE", COUNT (*) AS "VECES QUE SE REPITE" FROM EMPLOYEES GROUP BY FIRST_NAME;
 
/*Muestra el identificador del gerente y el salario del empleado más bajo pagado por ese gerente. Excluir cualquier registro donde el gerente no se conoce, excluir grupo en el que el salario mínimo sea menor de $6,000. Ordenar la salida con el salario descendente.*/
SELECT MANAGER_ID AS "NUMERO DEL GERENTE", MIN(SALARY) AS "SALARIO MAS BAJO PAGADO" FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL AND SALARY > 6000 GROUP BY MANAGER_ID ORDER BY 2 DESC;
 
/*Observar la estructura de la tabla DEPARTMENTS y seleccionar todos los datos de la tabla.*/
SELECT * FROM DEPARTMENTS;

/*Crear una consulta para mostrar LAST_NAME, JOB_ID, HIRE_DATE y EMPLOYEE_ID para cada empleado, con el número del empleado que aparezca primero.*/
SELECT EMPLOYEE_ID AS "IDENTIFICADOR", LAST_NAME AS "APELLIDO", JOB_ID AS "IDENTIFICADOR DE TRABAJO", HIRE_DATE AS "FECHA DE CONTRATO" FROM EMPLOYEES;
 
/*Crear una consulta para mostrar los únicos JOB_ID de la tabla EMPLOYEES.*/
SELECT DISTINCT(JOB_ID) AS "UNICOS IDENTIFICADORES" FROM EMPLOYEES;
 
/*Mostrar el LAST_NAME concatenado con JOB_ID, separado por una coma y un espacio, y nombrar la columna como “EMPLOYEE Y TITLE”.*/
SELECT CONCAT (CONCAT(LAST_NAME,', '), JOB_ID) AS "EMPLOYEE AND TITLE" FROM EMPLOYEES;
 
/*The HR department wants a query to display the LAST_NAME, JOB_ID, HIRE_DATE, and EMPLOYEE_ID for each employee, with employee number appearing first. Provide an alias STARTDATE for the HIRE_DATE column.*/
SELECT EMPLOYEE_ID AS "EMPLOYEE ID", LAST_NAME AS "LAST NAME", JOB_ID AS "JOB ID", HIRE_DATE AS "START DATE" FROM EMPLOYEES;
 
/*Crear una consulta para mostrar el apellido y el salario de los empleados que ganan más de $ 12.000.*/
SELECT LAST_NAME AS "APELLIDO", SALARY AS "SALARIO MAYOR A 12000" FROM EMPLOYEES WHERE SALARY > 12000;
 
/*Crear una consulta para mostrar el apellido del empleado y número de departamento para el empleado con número 176.*/
SELECT LAST_NAME AS "APELLIDO", DEPARTMENT_ID AS "IDENTIFICADOR DEL DEPARTAMENTO" FROM EMPLOYEES WHERE EMPLOYEE_ID = 176;
 
/*Mostrar el apellido y el salario de todos los empleados cuyo salario no está en el rango de $ 5.000 y $ 12.000.*/
SELECT LAST_NAME AS "APELLIDO", SALARY AS "SALARIO FUERA DEL RANGO" FROM EMPLOYEES WHERE SALARY < 5000 OR SALARY > 12000;
 
/*Mostrar el apellido del empleado, JOB_ID, y HIRE_DATE de los empleados contratados entre el 20 de febrero de 2001, y el 1 de mayo de 2005.*/
SELECT LAST_NAME AS "APELLIDO", JOB_ID AS "IDENTIFICADOR DE TRABAJO", TO_CHAR(HIRE_DATE, 'FMMONTH DD, YYYY' ) AS "FECHA DE CONTRATO" FROM EMPLOYEES WHERE HIRE_DATE >= TO_DATE('20-02-01','DD-MM-YY') AND HIRE_DATE <= TO_DATE('01-05-05','DD-MM-YY');
 
/*Crear un informe para mostrar el apellido del empleado y cargo de todos los empleados que no tienen un gerente.*/
SELECT EMPLOYEES.LAST_NAME AS "APELLIDO", JOBS.JOB_TITLE AS "CARGO" FROM EMPLOYEES INNER JOIN JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID WHERE EMPLOYEES.MANAGER_ID IS NULL;
                                                                                          
/*VISTAS*/
                                                                                          
CREATE OR REPLACE VIEW "FECHA" ("FECHA ACTUAL") AS SELECT SYSDATE FROM DUAL;
SELECT * FROM "FECHA";
DROP VIEW "FECHA";
                                                                                          
CREATE OR REPLACE VIEW "DATOS" ("EMPLEADO", "TRABAJO", "DEPARTAMENTO", "CIUDAD","PAIS", "CONTINENTE") AS SELECT CONCAT (CONCAT (EMPLOYEES.FIRST_NAME, ' '), EMPLOYEES.LAST_NAME) , JOBS.JOB_TITLE, DEPARTMENTS.DEPARTMENT_NAME , LOCATIONS.CITY, COUNTRIES.COUNTRY_NAME, REGIONS.REGION_NAME FROM EMPLOYEES INNER JOIN JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID INNER JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID INNER JOIN COUNTRIES ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID INNER JOIN REGIONS ON COUNTRIES.REGION_ID = REGIONS.REGION_ID;
SELECT * FROM "DATOS";
DROP VIEW "DATOS";
                                                                                          
CREATE OR REPLACE VIEW "TIEMPO LABORANDO" ("NOMBRE", "FECHA DE CONTRATO", "TIEMPO LABORANDO") AS SELECT CONCAT(CONCAT (EMPLOYEES.FIRST_NAME, ' '),EMPLOYEES.LAST_NAME), HIRE_DATE, CONCAT (ROUND (MONTHS_BETWEEN (SYSDATE, HIRE_DATE)/12), ' anios') FROM EMPLOYEES;
SELECT * FROM "TIEMPO LABORANDO";
DROP VIEW "TIEMPO LABORANDO";
                                                                                          
CREATE OR REPLACE VIEW "MIS DATOS" ("NOMBRE", "FECHA DE NACIMIENTO", "EDAD")
AS  SELECT CONCAT(CONCAT ('OLIVER', ' RIVERA'),' GONZALEZ') ,  TO_DATE('27-03-2000','DD-MM-YYYY'), TRUNC(MONTHS_BETWEEN (SYSDATE, TO_DATE('27-03-2000','DD-MM-YYYY'))/12)  FROM DUAL;
SELECT * FROM "MIS DATOS";
DROP VIEW "MIS DATOS";

CREATE OR REPLACE VIEW "DATOS DEL PRESIDENTE" ("NOMBRE", "CARGO", "CIUDAD", "PAIS") AS SELECT CONCAT(CONCAT (EMPLOYEES.FIRST_NAME, ' '),EMPLOYEES.LAST_NAME), JOBS.JOB_TITLE, LOCATIONS.CITY, COUNTRIES.COUNTRY_NAME FROM EMPLOYEES INNER JOIN JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID  INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID INNER JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID INNER JOIN COUNTRIES ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID WHERE EMPLOYEES.MANAGER_ID IS NULL;
SELECT * FROM "DATOS DEL PRESIDENTE";
DROP VIEW "DATOS DEL PRESIDENTE";

CREATE VIEW "TODAS LAS DIRECCIONES" ("ID DEL PAIS", "NOMBRE DEL PAIS", "ID DE LA CIUDAD","CIUDAD") AS SELECT COUNTRY_ID, COUNTRY_NAME, LOCATION_ID, CITY FROM LOCATIONS NATURAL JOIN COUNTRIES WITH READ ONLY;
SELECT * FROM “TODAS LAS DIRECCIONES”;
DROP VIEW “TODAS LAS DIRECCIONES”;

CREATE OR REPLACE VIEW  "EMPLEADOS MEXICANOS"("NOMBRE", "PAIS", "CIUDAD") AS SELECT CONCAT(CONCAT (EMPLOYEES.FIRST_NAME, ' '),EMPLOYEES.LAST_NAME), COUNTRIES.COUNTRY_NAME, LOCATIONS.CITY FROM EMPLOYEES INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID INNER JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID INNER JOIN  COUNTRIES ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID WHERE COUNTRIES.COUNTRY_ID LIKE 'MX';
SELECT * FROM "EMPLEADOS MEXICANOS";
DROP VIEW "EMPLEADOS MEXICANOS";
 
CREATE OR REPLACE VIEW  "EMPLEADOS BRITANICOS"("NOMBRE", "PAIS", "CIUDAD") AS SELECT CONCAT(CONCAT (EMPLOYEES.FIRST_NAME, ' '),EMPLOYEES.LAST_NAME), COUNTRIES.COUNTRY_NAME, LOCATIONS.CITY FROM EMPLOYEES INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID INNER JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID INNER JOIN COUNTRIES ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID WHERE COUNTRIES.COUNTRY_ID LIKE 'UK';
SELECT * FROM "EMPLEADOS BRITANICOS";
DROP VIEW "EMPLEADOS BRITANICOS";

CREATE OR REPLACE VIEW "GASTOS TOTALES" ("DEPARTAMENTO", "EMPLEADOS", "SALARIOS")AS SELECT DEPARTMENT_NAME, COUNT(EMPLOYEE_ID) , SUM(SALARY) FROM EMPLOYEES INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID GROUP BY DEPARTMENT_NAME;
SELECT * FROM "GASTOS TOTALES";
DROP VIEW "GASTOS TOTALES";

CREATE VIEW "COMISIONES"("IDENTIFICADOR","NOMBRE","DEPARTAMENTO","FECHA DE CONTRATO","COMISION") AS SELECT EMPLOYEE_ID, CONCAT(CONCAT (EMPLOYEES.FIRST_NAME, ' '),EMPLOYEES.LAST_NAME),DEPARTMENT_NAME,HIRE_DATE,SALARY*NVL(COMMISSION_PCT,.5) FROM EMPLOYEES INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID AND DEPARTMENT_NAME LIKE 'IT' ORDER BY FIRST_NAME || ' ' || LAST_NAME;
SELECT * FROM "COMISIONES";
DROP VIEW "COMISIONES";
 


